title: "Studies"
description: "A Central Hub for my Class Notes"
theme: just-the-docs

url: "https://harrisonbruechert.com"
baseurl: ""

aux_links: 
  "About Me": "/"
  "Studies": "/school"

#Color Scheme
color_scheme: dark

