title: "Harrison Bruechert"
description: "A Central Hub."
theme: just-the-docs

url: "https://harrisonbruechert.com"
baseurl: ""

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
